# -*- coding: utf-8 -*-
"""Image_Processing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EiJFSTJHDA515V787qou-YoGv5hWT87K
"""

import cv2
import numpy as np
from PIL import Image
import os
from IPython.display import Image
from google.colab.patches import cv2_imshow
import matplotlib.pyplot as plt
import tensorflow as tf

Image(filename = "kus.jpg")

img = cv2.imread('kus.jpg', cv2.IMREAD_GRAYSCALE)
img = img
plt.imshow(img, cmap= 'gray')
plt.show()

kernel = np.ones((5,5), np.uint8)
img_erosion = cv2.erode(img, kernel, iterations=1)
img_dilation = cv2.dilate(img, kernel, iterations=1)

cv2_imshow(img)
cv2_imshow(img_erosion)
cv2_imshow(img_dilation)

img = cv2.imread('kus.jpg')
retval, threshold = cv2.threshold(img, 125,255, cv2.THRESH_BINARY)
cv2_imshow(threshold)

img = cv2.imread('kus.jpg')
grayscaled = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
retval2, threshold2 = cv2.threshold(grayscaled, 152,255,cv2.THRESH_BINARY)

cv2_imshow(threshold2)

blurImg = cv2.blur(img, (10,10))
cv2_imshow(blurImg)

hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV) 
sobelx = cv2.Sobel(img,cv2.CV_64F,1,0,ksize=5)
sobely = cv2.Sobel(img,cv2.CV_64F,0,1,ksize=5)
laplacian = cv2.Laplacian(img,cv2.CV_64F) 

cv2_imshow(sobelx) 
cv2_imshow(sobely) 
cv2_imshow(laplacian)

Image(filename = "g.jpg")

img = cv2.imread('g.jpg', cv2.IMREAD_GRAYSCALE)
img = img
plt.imshow(img, cmap= 'gray')
plt.show()

kernel = np.ones((5,5), np.uint8)
img_erosion = cv2.erode(img, kernel, iterations=1)
img_dilation = cv2.dilate(img, kernel, iterations=1)

cv2_imshow(img)
cv2_imshow(img_erosion)
cv2_imshow(img_dilation)

img = cv2.imread('g.jpg')
retval, threshold = cv2.threshold(img, 125,255, cv2.THRESH_BINARY)
cv2_imshow(threshold)

grayscaled = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
retval2, threshold2 = cv2.threshold(grayscaled, 152,255,cv2.THRESH_BINARY)

cv2_imshow(threshold2)

blurImg = cv2.blur(img, (10,10))
cv2_imshow(blurImg)

hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV) 
sobelx = cv2.Sobel(img,cv2.CV_64F,1,0,ksize=5)
sobely = cv2.Sobel(img,cv2.CV_64F,0,1,ksize=5)
laplacian = cv2.Laplacian(img,cv2.CV_64F) 

cv2_imshow(sobelx) 
cv2_imshow(sobely) 
cv2_imshow(laplacian)

Image(filename="h.jpg")

img = cv2.imread('h.jpg', cv2.IMREAD_GRAYSCALE)
img = img
plt.imshow(img, cmap= 'gray')
plt.show()

kernel = np.ones((5,5), np.uint8)
img_erosion = cv2.erode(img, kernel, iterations=1)
img_dilation = cv2.dilate(img, kernel, iterations=1)

cv2_imshow(img)
cv2_imshow(img_erosion)
cv2_imshow(img_dilation)

img = cv2.imread('h.jpg')
retval, threshold = cv2.threshold(img, 125,255, cv2.THRESH_BINARY)
cv2_imshow(threshold)

grayscaled = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
retval2, threshold2 = cv2.threshold(grayscaled, 152,255,cv2.THRESH_BINARY)

cv2_imshow(threshold2)

blurImg = cv2.blur(img, (10,10))
cv2_imshow(blurImg)

hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV) 
sobelx = cv2.Sobel(img,cv2.CV_64F,1,0,ksize=5)
sobely = cv2.Sobel(img,cv2.CV_64F,0,1,ksize=5)
laplacian = cv2.Laplacian(img,cv2.CV_64F) 

cv2_imshow(sobelx) 
cv2_imshow(sobely) 
cv2_imshow(laplacian)