# -*- coding: utf-8 -*-
"""IP_with_functions.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yUxFYFYD30PUkf6ZKSUl8tn3_VzPd7yB
"""

import cv2
import numpy as np
from PIL import Image as IMAGE
import os
from IPython.display import Image
from google.colab.patches import cv2_imshow
import matplotlib.pyplot as plt
import tensorflow as tf

IMAGE.open("kus.jpg")

def doGray(name):
  img = cv2.imread(name, cv2.IMREAD_GRAYSCALE)
  img = img
  plt.imshow(img, cmap= 'gray')
  plt.show()

doGray('kus.jpg')

def show_erosion(name):
  kernel = np.ones((5,5), np.uint8)
  img = cv2.imread(name, cv2.IMREAD_GRAYSCALE)
  img_erosion = cv2.erode(img, kernel, iterations=1)
  cv2_imshow(img_erosion)

show_erosion('kus.jpg')

def show_dilation(name):
  kernel = np.ones((5,5), np.uint8)
  img = cv2.imread(name, cv2.IMREAD_GRAYSCALE)
  img_dilation = cv2.dilate(img, kernel, iterations=1)
  cv2_imshow(img_dilation)

show_dilation('kus.jpg')

def show_threshold(name):
  img = cv2.imread(name)
  retval, threshold = cv2.threshold(img, 125,255, cv2.THRESH_BINARY)
  cv2_imshow(threshold)

show_threshold('kus.jpg')

def show_threshold2(name):
  img = cv2.imread(name)
  grayscaled = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
  retval2, threshold2 = cv2.threshold(grayscaled, 152,255,cv2.THRESH_BINARY)
  cv2_imshow(threshold2)

show_threshold2('kus.jpg')

def do_blur(name):
  img = cv2.imread(name)
  blurImg = cv2.blur(img, (10,10))
  cv2_imshow(blurImg)

do_blur('kus.jpg')

def show_sobel(name,label):
  img = cv2.imread(name)
  hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV) 
  if label == 'x' :
    sobelx = cv2.Sobel(img,cv2.CV_64F,1,0,ksize=5)
    cv2_imshow(sobelx)
  if label == 'y' :
    sobely = cv2.Sobel(img,cv2.CV_64F,0,1,ksize=5)
    cv2_imshow(sobely)

show_sobel('kus.jpg','x')
show_sobel('kus.jpg','y')

def show_laplacian(name):
    img = cv2.imread(name)
    hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV) 
    laplacian = cv2.Laplacian(img,cv2.CV_64F)  
    cv2_imshow(laplacian)

show_laplacian('kus.jpg')

doGray('g.jpg')
doGray('h.jpg')

show_erosion('g.jpg')
show_erosion('h.jpg')

show_dilation('g.jpg')
show_dilation('h.jpg')

show_threshold('g.jpg')
show_threshold('h.jpg')

show_threshold2('g.jpg')
show_threshold2('h.jpg')

do_blur('g.jpg')
do_blur('h.jpg')

show_sobel('g.jpg','x')
show_sobel('g.jpg','y')

show_sobel('h.jpg','x')
show_sobel('h.jpg','y')

show_laplacian('g.jpg')
show_laplacian('h.jpg')

